apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: dev

  SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/appdb
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
