apiVersion: v1
kind: Service
metadata:
  name: springapp-service
  namespace: qa
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
